config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    post 'api/login' => 'api_authentication#create'
    get 'user/sso' => 'sso#create'
  end

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    require 'sidekiq-scheduler/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'search#index'
  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  get 'author/:author_id' => 'author#index', :as => :author_by_id
  get 'faq' => 'pages#faq', :as => :faq
  get 'about' => 'pages#about', :as => :about
  get 'search' => 'search#search', :as => :search
  get 'search/id/:search_id' => 'search#search', :as => :search_by_id
  post 'search/click' => 'search#click', :as => :search_click
  post 'search/report_broken' => 'search#report_broken', :as => :search_report_broken
  get 'characters' => 'search#characters'
  get 'crossovers' => 'search#crossovers'
  get 'omni' => 'search#omni'
  post 'pensieve#bookmark' => 'pensieve#bookmark'
  match 'pensieve#bookmark' => 'pensieve#bookmark', :via => :options

  namespace :api do
    namespace :v1 do
      get 'stories/:id' => 'stories#show', :defaults => { :format => 'json' }
    end
  end

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  namespace :user do
    get 'queue' => 'queue_entries#index', :as => :queue_entries
    post 'queue' => 'queue_entries#create'
    delete 'queue' => 'queue_entries#destroy'
    resources :saved_searches
    get 'recommendations' => 'recommendations#index', :as => :recommendations

    get 'hidden' => 'hidden#index'
    put 'hidden/author' => 'hidden#hide_author'
    delete 'hidden/author' => 'hidden#unhide_author'
    put 'hidden/story' => 'hidden#hide_story'
    delete 'hidden/story' => 'hidden#unhide_story'

  end
  resources :feedback

  get 'crawl/generate_assignments'
  get 'crawl/indexed_fandoms'
  post 'crawl/update_checkpoint'

  get 'dm', to: proc { [200, {}, ['']] }

end

app/models/search.rb
require 'scryer/constants'

class Search < ActiveRecord::Base
  after_initialize :init

  validates :wordcount_lower, :wordcount_upper, :favorites_lower, :favorites_upper, :chapters_lower, :chapters_upper,
            :average_words_per_chapter_lower,
            numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2**31-1},
            allow_nil: true
  validates :fandoms, presence: true
  validates :category_required, :length => { :maximum => 2, :message => 'may have at most 2 categories'}
  validates :character_required, :length => { :maximum => 4, :message => 'may have at most 4 characters' }
  validates :status, inclusion: {in: Scryer::Constants::STATUS.values}
  validates :read_filter, inclusion: {in: Scryer::Constants::READ_FILTER.values}, presence: true
  validates :order_by, inclusion: {in: Scryer::Constants::ORDERING.values}, presence: true
  validates :category_optional_exclude, :character_optional_exclude, :inclusion => {:in => [true, false]}
  validates_each :fandoms,
                 :crossovers,
                 :character_required,
                 :character_optional,
                 :category_required,
                 :category_optional do |record, attr, value|
    if !value.nil? && !value.all? { |v| v.is_a?(Integer) }
      record.errors.add(attr, "collection is not an all integers: #{value}")
    end
  end
  validate :validate_sort_by
  validate :validate_ratings
  validate :validate_crossover_options

  belongs_to :user, optional: true
  # has_many :tags_include, :class_name => 'Tag'
  # has_many :tags_exclude, :class_name => 'Tag'

  @@fields = Set.new(%w(fandoms crossovers include_source_fandoms exclude_crossover_fandoms title author summary
                category_required category_optional category_optional_exclude
                character_required character_optional character_optional_exclude
                relationships
                tags_include tags_exclude
                language status rating, read_filter
                wordcount_lower wordcount_upper chapters_lower chapters_upper, average_words_per_chapter_lower
                updated_before updated_after published_before published_after
                favorites_lower favorites_upper
                sort_by order_by).map{|f| f.to_sym})

  def init
    # Default values

    self.fandoms                          ||= [224]
    self.crossovers                       ||= []
    self.include_source_fandoms           ||= false
    self.exclude_crossover_fandoms        ||= false
    self.title                            ||= ''
    self.author                           ||= ''
    self.summary                          ||= ''
    self.category_required                ||= []
    self.category_optional                ||= []
    self.category_optional_exclude        ||= false
    self.character_required               ||= []
    self.character_optional               ||= []
    self.character_optional_exclude       ||= false
    self.relationships                    ||= []
    self.tags_include_ids                 ||= []
    self.tags_exclude_ids                 ||= []
    self.language                         ||= 'english'
    self.status                           ||= ''
    self.read_filter                      ||= 'all'
    self.rating                           ||= Scryer::Constants::RATING.values
    self.wordcount_lower                  ||= nil
    self.wordcount_upper                  ||= nil
    self.favorites_lower                  ||= nil
    self.favorites_upper                  ||= nil
    self.chapters_lower                   ||= nil
    self.chapters_upper                   ||= nil
    self.average_words_per_chapter_lower  ||= nil
    self.published_before                 ||= nil
    self.published_after                  ||= nil
    self.updated_before                   ||= nil
    self.updated_after                    ||= nil
    self.sort_by                          ||= '_score'
    self.order_by                         ||= 'desc'

    # Fix rating
    self.rating.collect! do |rating|
      if rating == 'k+' or rating == 'k '
        'kplus'
      else
        rating
      end
    end

    # Fix relationships
    if self.relationships.is_a? Hash
      self.relationships = self.relationships.values.collect do |ship|
        if ship['characters'] && !ship['characters'].empty?
          ship
        else
          nil
        end
      end.compact
    end
  end

  def execute(user, page, per_page)
    SearchResults.new(
        SearchQuery.new.execute(user, self, (page-1)*per_page, per_page),
        page,
        per_page)
  end

  def allow_stale_results?
    false
  end

  def merged_fandoms
    f = fandoms
    if crossovers
      f += crossovers
    end

    f
  end

  def tags_include
    Tag.where id: tags_include_ids
  end

  def tags_exclude
    Tag.where id: tags_exclude_ids
  end

  def self.from_hash(h)
    # unknown property??
    h.delete('fandom')

    h.each do |k,v|
      if v.is_a?(Array)
        h[k] = v.reject{|v2| v2.nil? || v2 == '' }
      end
    end

    Search.new(h)
  end

  def to_hash
    self.attributes.select { |k,v| @@fields.include?(k.to_sym) && v != nil && v != [nil] }
  end

  def to_reduced_hash
    self.attributes.select { |k,v| @@fields.include?(k.to_sym) && v != nil && v != '' && v != [nil] && v != [] && v }
  end

private
  def validate_ratings
    diff = rating-Scryer::Constants::RATING.values
    unless diff.empty?
      errors.add(:rating, "contains unsupported values, found: #{diff}, allowed: #{Scryer::Constants::RATING.values}")
    end
  end
  def validate_sort_by
    unless Scryer::Constants::SORTING.values.include?(sort_by)
      errors.add(:sort_by, "contains unsupported values, found: #{sort_by}, allowed: #{Scryer::Constants::SORTING.values}")
    end
  end
  def validate_crossover_options
    if crossovers.include? -1 and exclude_crossover_fandoms
      errors.add(:crossovers, "cannot exclude all crossovers")
    end
  end
end

class SearchResults
  attr_reader :search, :results, :hits, :pagination

  def initialize(search_results, page, per_page)
    @search = search_results
    @page = page
    @per_page = per_page
    @hits = @search['hits']


    story_ids = @search['results'].map { |result| result['story_id'] }
    stories_by_id = Story.where(:id => story_ids)
                   .includes([:author, :story_to_thread])
                   .joins([:author])
                   .index_by(&:id)
    @results = story_ids
                   .map do |id|
      story = stories_by_id[id]
      if story.nil?
        Rails.logger.warn "search: Couldn't find Story(#{id})"
      end
      story
    end.compact


    @pagination = Kaminari.paginate_array(@results, total_count: @hits).page(@page).per(@per_page)
  end
end

app/controllers/search_controller.rb
require 'hashie/mash'
require 'scryer/constants'
require 'scryer/exceptions'

class SearchController < ApplicationController

  before_action :extract_search, :except => 'report_broken'
  skip_before_action :verify_authenticity_token, :only => 'click'

  def index
    if @search.exclude_crossover_fandoms
      @characters = Character.for_fandoms(@fandoms, @crossovers)
    else
      @characters = Character.for_fandoms(@fandoms, [])
    end

    @fandom_facets = Fandom.fandom_facets(@fandoms)
    @tags = Tag.all.order(:id)
  end

  def omni

  end

  def report_broken
    BrokenLinkWorker.perform_async(params[:story_id].to_i)

    render status: 202, plain: 'OK'
  end

  def search
    if @search == {} || !@search
      redirect_to({ :action => :index }, alert: 'You must provide a valid search.')
      return
    end

    @page = (params[:page] || '1').to_i

    unless @search.valid?
      if @search.exclude_crossover_fandoms
        @characters = Character.for_fandoms(@fandoms, @crossovers)
      else
        @characters = Character.for_fandoms(@fandoms, [])
      end
      @fandom_facets = Fandom.fandom_facets(@fandoms)
      @tags = Tag.all.order(:id)
      render 'index'
      return
    end

    @search_results = @search.execute(current_user, @page, 25)
    @story_context = StoryFetchContext.new(current_user, @search_results.results.map(&:id))
  rescue Elasticsearch::Transport::Transport::Errors::BadRequest => e
    structured_error = JSON.parse(e.message[6..-1])

    client_error_type = structured_error.dig('error', 'caused_by', 'caused_by', 'type')
    client_error_message = structured_error.dig('error', 'caused_by', 'caused_by', 'reason')

    error_string = 'Search failed: '
    if client_error_type.nil?
      error_string += 'Unknown error. :('
    else
      error_string += "#{client_error_type}: #{client_error_message}"
    end

    redirect_to(root_path(params.permit!), flash: { error: error_string})
    return
  rescue Exceptions::InvalidSearchError => e
    redirect_to(root_path(params.permit!), flash: { error: "Search failed: #{e.message}"})
    return
  end

  def click
    record_click(params)
  end

  def crossovers
    @fandom_facets = Fandom.fandom_facets(params[:fandom] || [])

    respond_to do |format|
      format.json { render json: @fandom_facets }
    end
  end

  def characters
    fandoms = (params[:fandom] || []).map(&:to_i)
    exclude_fandoms = (params[:exclude_fandom] || []).map(&:to_i)
    @characters = Character.for_fandoms(fandoms, exclude_fandoms)

    respond_to do |format|
      format.json { render json: @characters }
    end
  end

private
  def record_click(event)
    story_id = event['story_id']
    story_update_id = StoryUpdate.where(story_id: story_id).select(:id).order('id DESC').first.try(:id)
    user_id = nil
    ip = request.remote_ip
    user_agent = request.user_agent
    page = event['page'].to_i
    origin = event['origin']

    if current_user
      user_id = current_user.id
    end

    search = event['search']
    StoryClick.new(
                  story_id: story_id,
                  story_update_id: story_update_id,
                  user_id: user_id,
                  search: search,
                  page: page,
                  origin: origin,
                  ip: ip,
                  user_agent: user_agent
    ).save

    render status: 201, plain: 'OK'
  end

  def extract_search
    @search = params[:search]
    unless @search.is_a?(ActionController::Parameters)
      @search = ActionController::Parameters.new({})
    end

    if !params[:saved_search_id].blank?
      @saved_search = SavedSearch.find(params[:saved_search_id])
    end

    if !params[:search_id].blank?
      @saved_search = SavedSearch.find(params[:search_id])

      if @saved_search
        @search = @saved_search.search
        @search_params = ActionController::Parameters.new(@search.to_hash).permit!

        @crossovers = @search.crossovers
        if @search.exclude_crossover_fandoms
          @fandoms = @search.fandoms
        else
          @fandoms = [*@search.fandoms] + [*@search.crossovers]
        end

        return
      end
    end

    # Some clients seem to transform search[fandoms][]=4 into search[fandoms][1]=4.
    [:fandoms, :crossovers, :rating].each do |key|
      if @search[key].is_a?(ActionController::Parameters)
        @search[key] = @search[key].values
      end
    end

    (@search[:fandoms] || []).map!(&:to_i)
    (@search[:crossovers] || []).map!(&:to_i)
    @search['crossovers'] = ([] << @search['crossovers']).flatten if @search['crossovers']

    @search_params = @search.permit!
    @search = Search.from_hash(@search.permit!)

    @crossovers = @search['crossovers'].compact
    if @search.exclude_crossover_fandoms
      @fandoms = @search['fandoms'].compact
    else
      @fandoms = [@search['fandoms'], @search['crossovers']].flatten.compact
    end
  end
end

app/helpers/search_helper.rb
require 'pp'

module SearchHelper
  def story_pp(story)
    ''
  end

  def extract_names(vals, join_char=' ')
    vals.collect { |c| c.name }.join(join_char)
  end

  def show_characters(context, story)
    # categories.collect { |c| c.name }.join(join_char)

    unbound_characters = context.characters(story).collect { |c| c.name }

    relationships = context.relationships(story)
    bound_characters = relationships.flatten.collect { |c| c.name }

    # Remove characters that'll be formatted with pairing brackets
    unbound_characters.delete_if { |c| bound_characters.index(c) }

    # Colors for relationships
    colors = %w(primary danger warning success)

    formatted_relationships = relationships.collect do |relationship|
      color = colors.pop
      content_tag(:span, class: "text-#{color}") do
        [
          content_tag(:i, '', class: 'fa fa-margin fa-angle-left'),
          extract_names(relationship, ', '),
          content_tag(:i, '', class: 'fa fa-margin fa-angle-right')
        ].join.html_safe
      end.html_safe
    end

    (formatted_relationships + unbound_characters).join(', ').html_safe
  end

  def classify(context, story, &block)
    tags = []
    Rack::MiniProfiler.step('ContentTagger') do
      tags = Scryer::Tagging::ContentTagger.generate_story_tags(story, context.relationships(story)).map do |label|
        modifier = 'warning'
        if label =~ /slash/i
          modifier = 'danger'
        end

        content_tag(:span, label.to_s.gsub('_', ' '), class: "label label-#{modifier}")
      end
    end

    if tags.blank?
      ''
    else
      "#{tags.join(' ')} #{capture(&block)}".html_safe
    end
  end

  def has_results?
    @search_results.hits > 0 && @search_results.results.size > 0
  end

  def included_text(excluded, item_type)
    "#{excluded ? 'Excluded' : 'Included'} #{item_type}"
  end
end

app/views/search/_empty.html.erb
<div class="page-header borderless">
  <h1>No results found :(</h1>
  <p class="lead">
    <%= link_to 'Try another search.', root_path(search: @search_params) %>
  </p>
</div>

app/views/search/_omnisearch.html.erb
<form action="/search" method="GET">
  <div class="input-group">
    <span class="input-group-addon"><i class="icon-book"></i></span>
    <input id="omnisearch" name="query" type="text" class="form-control" placeholder="Search for a story, author, or category" autocomplete="on" autofocus="autofocus" />
    <span class="input-group-btn"><input type="submit" class="btn btn-default btn-group" value="Search" /></span>
  </div>
</form>

app/views/search/_relationship_row.html.erb
<div class="form-group col-lg-12 shiprow" data-ship-index="<%= index -%>">
  <div class="input-group">
    <span class="input-group-addon">
      <%= check_box_tag "search[relationships][#{index}][partial]", true, ship.key?('partial'), class: 'ship_partial' %>
      Partial
    </span>
    <span class="input-group-addon">
      <%= check_box_tag "search[relationships][#{index}][exclude]", true, ship.key?('exclude'), class: 'ship_exclude' %>
      Exclude
    </span>
    <select multiple
            class="form-control character_list"
            data-placeholder="Choose up to 4 characters"
            name="search[relationships][<%= index -%>][characters][]"
            id="search[relationships][<%= index -%>][characters][]">
      <option disabled></option>
      <%= options_from_collection_for_select(@characters, :id, :name, ship['characters'] || []) %>
    </select>
    <span class="input-group-btn">
      <button id="remove_relationships[<%= index -%>]" class="btn btn-default btn-sm" type="button" <% if index == 0 %>disabled="disabled"<% end %>>Remove</button>
    </span>
  </div>
</div>

app/views/search/_saved_search_modal.html.haml
.modal.fade{:id => 'savedsearchModal'}
  .modal-dialog
    .modal-content
      = form_for([:user, @current_user.saved_searches.build], remote: true) do |f|
        .modal-header
          %button.close{:type=>'button','data-dismiss'=>'modal'}
            &times;
          %h4.modal-title
            Saved Search
        .modal-body
          .form-group
            %label{:for => 'name'}
              Name your search
            = f.text_field :name, :class => 'form-control'
            %hr
            %label{:for => 'saved_search_id'}
              Or choose existing to update
            = f.collection_select :id, @current_user.saved_searches, :hash_id, :name,
                {include_blank: 'Create new search', selected: @saved_search.try(:hash_id)},
                :class => 'form-control'
            - @search_params.each do |k,v|
              - if k == 'relationships'
                - v.each do |k1, v1|
                  - if v1['characters']
                    = hidden_field_tag "save_search[relationships][#{k1}][partial]", true if v1.key?('partial')
                    = hidden_field_tag "save_search[relationships][#{k1}][exclude]", true if v1.key?('exclude')
                    - v1['characters'].each do |c|
                      = hidden_field_tag "save_search[relationships][#{k1}][characters][]", c
              - elsif v.kind_of? Array
                - v.each do |v1|
                  = hidden_field_tag "save_search[#{k}][]", v1
              - else
                = hidden_field_tag "save_search[#{k}]", v
        .modal-footer
          %button.btn.btn-default{:type => 'button', 'data-dismiss' => 'modal'}
            Nevermind
          %button.btn.btn-success{:type => 'submit'}
            Submit

app/views/search/_story_result.html.erb
<% debug_value = {} if local_assigns[:debug_value].nil? %>
<% origin = nil if local_assigns[:origin].nil? %>

<div class="panel panel-default">
  <div class="panel-heading">
    <% if story_result.story_to_thread %>
        <a
        href="https://forums.darklordpotter.net/threads/<%= story_result.story_to_thread.thread_id %>/"
        data-thread-id="<%= story_result.story_to_thread.thread_id %>"
        class="pull-right thread-link">
        DLP <%= number_with_precision(story_result.story_to_thread.score, precision: 2) %> <i class="fa fa-star"></i></a>
    <% end %>
    <% if context.read?(story_result) %>
        <a
            class="pull-right thread-link"
            data-story="<%= story_result.title %>"
            target="_blank"
            rel="nofollow noopener"
            href="https://www.fanfiction.net/s/<%= story_result.id %>/<%= [context.read?(story_result)+1, story_result.chapters].min %>">
          <i class="fa fa-check" title="Read up to chapter <%= context.read?(story_result) %>"></i>
          <% if context.read?(story_result) < story_result.chapters %>
            <%= story_result.chapters - context.read?(story_result) %> chapters available
          <% end %>
        </a>
    <% end %>
    <h3 class="panel-title">
      <a
              class="story-link"
              data-story="<%= story_result.title %>"
              data-story-origin="<%= origin %>"
              data-story-id="<%= story_result.id %>"
              rel="nofollow noopener"
              target="_blank"
              href="<%= story_result.url %>"><%= story_result.title %></a>
      by
      <a
              class="author-link"
              data-author="<%= story_result.author.id %>"
              rel="nofollow noopener"
              target="_blank"
              href="<%= story_result.author.url %>"><%= story_result.author.name %></a>

      <% if Rails.env.development? %>
          <i class="fa fa-list" title="<%= debug_value.try(:inspect) %>" data-toggle="tooltip"></i>
      <% end %>
      <% if context.opened?(story_result) and !context.read?(story_result) %>
          <i class="fa fa-eye pull-right" title="Last opened <%= context.opened?(story_result).created_at %>"></i>
      <% end %>
      <% if story_result.stale? %>
          <span
            class="label label-danger"
            title="Story may no longer exist, reindexing operations haven't seen this result recently.">
              Stale Result (Last seen: <%= timeago_tag story_result.last_seen %>)
          </span>
      <% end %>
    </h3>
  </div>
  <div class="story-summary panel-body">
    <%= story_result.summary %>
    <div>
      <hr />
      <%= classify(context, story_result) do %>
        <i class="text-muted fa fa-question-circle xsmall"
           title="Content tags are derived from story attributes such as the summary and characters."></i>
      <% end %>
      <span class="pull-right">
        <div class="btn-group">
        <% if current_user %>
          <% if context.queued?(story_result)%>
            <button type="button" data-story-id="<%= story_result.id -%>" data-state="in-queue" class="read-it-later btn btn-xs btn-default text-muted">
              <i class="fa fa-minus"></i>
              Remove from queue
            </button>
          <% else %>
            <button type="button" data-story-id="<%= story_result.id -%>" data-story-origin="<%= origin %>" data-state="out-of-queue" class="read-it-later btn btn-xs btn-default text-muted">
              <i class="fa fa-plus"></i>
              Add to queue
            </button>
          <% end %>
          <button type="button" class="hide-story btn btn-xs btn-default text-muted" data-story-id="<%= story_result.id -%>">
            <i class="fa fa-eye-slash"></i>
            Hide Story
          </button>
        <% end %>
          <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Other stories by Author', author_by_id_path(story_result.author) %></li>
            <% if current_user %>
              <li role="separator" class="divider"></li>
              <li><a class="hide-author" data-author-id="<%= story_result.author.id -%>">Hide Stories by Author</a></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li>
              <a class="report-broken" data-story-id="<%= story_result.id %>" title="Flag as broken link">
                <i class="fa fa-flag"></i> Report Broken Link
              </a>
            </li>
          </ul>
        </div>


      </span>
    </div>
  </div>
  <div class="panel-footer small">
    <%
      story_fandoms = context.fandoms(story_result)
      selected_fandoms = if @search
                            @search.fandoms
                          else
                            [story_fandoms[0].id]
                          end
       selected_crossovers = if @search
                               @search.crossovers
                             else
                               []
                             end

       fandom = story_fandoms
           .select { |f| selected_fandoms.include?(f.id) }
           .first
       crossover = story_fandoms
           .select { |f| f != fandom }
           .first
    %>
    <% if selected_fandoms.size > 1 && fandom %>
        <% if story_result.crossover? %>
            <i class="fa fa-random"></i>
            <%= fandom.name %> x <%= crossover.name %>
        <% else %>
            <i class="fa fa-book"></i>
            <%= story_fandoms[0].name %>
        <% end %>
        -
    <% elsif (selected_crossovers.size > 0 or (@fandoms && @fandoms.include?(-1))) && crossover %>
        <i class="fa fa-random"></i>
        <%= crossover.name %>
        -
    <% end %>
    <% unless @fandoms %>
        <% if story_result.crossover? %>
            <i class="fa fa-random"></i>
            <%= story_fandoms.map(&:name).join(' x ') %>
        <% else %>
            <i class="fa fa-book"></i>
            <%= story_fandoms[0].name %>
        <% end %>
        -
    <% end %>
    <span class="pull-right text-muted"
          title="Updated: <%= story_result.updated %>"
          am-time-ago="item.updated"><%= timeago_tag story_result.updated, :limit => 2.years.ago %></span>
    <strong title="Published: <%= story_result.published %>">
      <%= story_result.status %>
    </strong>
    - <%= Scryer::Constants::RATING.key(story_result.rated.downcase) %>
    - <%= extract_names(context.categories(story_result), '/') %>
    - <%= show_characters(context, story_result) %>
    - <%= number_with_delimiter(story_result.words) %> words
    - <%= pluralize(story_result.chapters, 'chapter') %>
    - <%= number_with_delimiter(story_result.reviews) %> reviews
    <span class="text-muted">
      - <%= number_with_delimiter(story_result.favs) %> favorites
      - <%= number_with_delimiter(story_result.follows) %> follows
    </span>
  </div>
</div>

app/views/search/omni.html.haml
.page-header
  %h1 Omnisearch Test
  = render :partial => 'omnisearch'

app/views/search/search.html.erb
<% if has_results? %>
    <h4>
      <% if @saved_search %>
          <div>
            Search: <strong><%= @saved_search.name %></strong>
          </div>

      <% end %></h4>
    <h4 class="page-header">
      <%= link_to 'Search', root_path(search: @search_params, saved_search_id: params[:saved_search_id]) %>
      in
      <%= Fandom.name_sentence(@fandoms) %>
      <% if @fandoms.include? -1 %>
          and All Crossovers
      <% elsif @search.exclude_crossover_fandoms %>
          and All Crossovers excluding <%= Fandom.name_sentence(@crossovers) %>
      <% end %>
      <small><%= number_with_delimiter(@search_results.hits) %> Stories Found</small>
    </h4>
    <% if user_signed_in? %>
        <%= render 'search/saved_search_modal' %>
        <div class="pull-right">
          <a data-toggle="modal"
             data-target="#savedsearchModal"
             class="btn btn-success btn-block btn-sm"
             style="margin-bottom:5px">
            Save Search</a>
        </div>
    <% end %>
    <!-- TODO: graphs/stats -->
    <!-- TODO: Drilldown links / facets -->

    <% content_for(:pagination_info) do %>
        <%= page_entries_info @search_results.pagination %>
    <% end %>
    <% content_for(:pagination) do %>
      <%= paginate @search_results.pagination %>
    <% end %>

    <div>
      <%= yield :pagination_info %>
    </div>
    <div class="text-right">
      <%= yield :pagination %>
    </div>

    <div class="clearfix"></div>
<% end %>
<div id="search" data-search="<%= @search.to_json %>">
  <%= (render :partial => 'story_result', :locals => {context: @story_context, origin: 'search'}, :collection => @story_context.stories) || (render :partial => 'empty') %>
</div>

<% if has_results? %>
    <div>
      <%= yield :pagination_info %>
    </div>
    <div class="text-right">
      <%= yield :pagination %>
    </div>
<% end %>