config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    post 'api/login' => 'api_authentication#create'
    get 'user/sso' => 'sso#create'
  end

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    require 'sidekiq-scheduler/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'search#index'
  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'
  get 'author/:author_id' => 'author#index', :as => :author_by_id
  get 'faq' => 'pages#faq', :as => :faq
  get 'about' => 'pages#about', :as => :about
  get 'search' => 'search#search', :as => :search
  get 'search/id/:search_id' => 'search#search', :as => :search_by_id
  post 'search/click' => 'search#click', :as => :search_click
  post 'search/report_broken' => 'search#report_broken', :as => :search_report_broken
  get 'characters' => 'search#characters'
  get 'crossovers' => 'search#crossovers'
  get 'omni' => 'search#omni'
  post 'pensieve#bookmark' => 'pensieve#bookmark'
  match 'pensieve#bookmark' => 'pensieve#bookmark', :via => :options

  namespace :api do
    namespace :v1 do
      get 'stories/:id' => 'stories#show', :defaults => { :format => 'json' }
    end
  end

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unacceptable'
  get '/500', :to => 'errors#internal_error'

  namespace :user do
    get 'queue' => 'queue_entries#index', :as => :queue_entries
    post 'queue' => 'queue_entries#create'
    delete 'queue' => 'queue_entries#destroy'
    resources :saved_searches
    get 'recommendations' => 'recommendations#index', :as => :recommendations

    get 'hidden' => 'hidden#index'
    put 'hidden/author' => 'hidden#hide_author'
    delete 'hidden/author' => 'hidden#unhide_author'
    put 'hidden/story' => 'hidden#hide_story'
    delete 'hidden/story' => 'hidden#unhide_story'

  end
  resources :feedback

  get 'crawl/generate_assignments'
  get 'crawl/indexed_fandoms'
  post 'crawl/update_checkpoint'

  get 'dm', to: proc { [200, {}, ['']] }

end

app/views/layouts/_flash.html.erb
<div class="alert alert-<%= flash_class(level) %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <%= flash[level] %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <img src="/dm/" width="0" height="0" />
    <div class="container">
    <% if user_signed_in? && current_user %>
        <p class="pull-right small">Logged in as <%= current_user.try(:username) %></p>
    <% end %>
    <div>
      © <%= Date.today.year %> DLP Group
    </div>
    <div>
      <span class="small">
        <a href="https://gitlab.com/projectdlp/scryer">Scryer</a> 2.0-<%= "#{GIT_COMMIT}@#{GIT_BRANCH}" %>
        <%= Rails.env %>
      </span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top navbar-inverse navbar-<%= Rails.env %>" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand <%= active_link(root_path) %>" href="/">
          <i class="fa fa-flash lightning-icon"></i>Scryer
          <% if Rails.env.development? %><strong> DEVELOPMENT</strong>
          <% end %></a>

        <p class="navbar-text"><em><%= raw Rails.configuration.taglines.sample %></em></p>
      </div>
      <ul class="nav navbar-nav nav-pills navbar-right">
        <li><a id="darkmode" href="#">🌓</a></li>
        <% if user_signed_in? %>
          <% if feature_active?(:recommender) %>
            <li class="<%= active_link(user_recommendations_path) %>"><%= link_to 'Recommendations', user_recommendations_path %></li>
          <% end %>
            <% if @current_user.queue_entries_count > 0 %>
              <li class="<%= active_link(user_queue_entries_path) %>"><%= link_to "Queue (#{@current_user.queue_entries_count})", user_queue_entries_path %></li>
            <% else %>
              <li class="<%= active_link(user_queue_entries_path) %>"><%= link_to "Queue", user_queue_entries_path %></li>
            <% end %>
            <li class="<%= active_link(user_saved_searches_path) %>"><%= link_to 'Searches', user_saved_searches_path %></li>
            <li><a data-toggle="modal" data-target="#feedbackModal">Give Feedback</a></li>
        <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
        <li><a href="https://forums.darklordpotter.net">DLP</a></li>
        <li class="<%= active_link(about_path) %>"><%= link_to 'About', about_path %></li>
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <% unless current_user.confirmed? %>
                    <i class="fa fa-exclamation-triangle" title="Unconfirmed account"></i>
                <% end %>
                <%= current_user.username %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Manage Hidden', user_hidden_path %></li>
                <!--<li class="icon-bar"><i class="icon-wrench"></i><a href="#">Settings</a></li>-->
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scryer<%= content_for?(:title) ? " :: #{content_for(:title)}" : '' %></title>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_pack_tag 'stylesheets' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag favicon_name %>
  <meta name="viewport" content="width=device-width">
  <meta name="theme-color" content="#324e2f"/>
</head>
<body class="<%= controller_name %>_controller <%= cookies['themeSwitch'] == 'dark' ? 'theme-dark' : '' %>" data-controller="<%= controller_name %>" data-action="<%= action_name %>">

<%= render 'layouts/header' %>
<%= render 'feedback/modal' %>
<div class="container <%= controller_name %>_controller">
  <% Announcement.current(cookies.signed[:hidden_announcement_ids]).each do |announcement| %>
      <%= div_for announcement, class: 'alert alert-info' do %>
          <i class="fa fa-bullhorn" aria-hidden="true"></i>
          <%= sanitize announcement.message %>
          <%= link_to '&times;'.html_safe, hide_announcement_path(announcement), remote: true, class: 'close', rel: 'nofollow' %>
      <% end %>
  <% end %>
  <% if current_user && !current_user.confirmed? %>
      <div class="alert alert-warning">
        <i class="fa fa-exclamation-triangle"></i>

        Your account's is currently email address unconfirmed. Your account will become inaccessible if not confirmed
        within 24 hours.
        <p>
          <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path %>
        </p>
      </div>
  <% end %>

  <div id="flash">
  </div>
  <% [:notice, :error, :alert].each do |level| %>
      <% unless flash[level].blank? %>
          <%= render :partial => 'layouts/flash', :locals => {:level => level} %>
      <% end %>
  <% end %>
  <%= yield %>
</div>

<%= render :partial => 'layouts/footer' %>

<script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

   ga('create', 'UA-442860-6');
   ga('send', 'pageview');
   <% if user_signed_in? && current_user %>
    ga('set', '&uid', '<%= current_user.try(:id) %>');
   <% end %>
</script>
</body>
</html>